# Generated by Django 4.1.4 on 2023-02-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('theke_pe_kam', 'Theke Pe Kam'), ('individuals_sahayak', 'Individuals Sahayak'), ('machine_job', 'Machine Job')], max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sahayak_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Booked', 'Booked'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('machine_malik_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Booked', 'Booked'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=20)),
                ('machine_type', models.CharField(blank=True, max_length=20)),
                ('job_description', models.TextField(blank=True)),
                ('job_land_size', models.CharField(blank=True, max_length=20)),
                ('pay_amount_male', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pay_amount_female', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('num_days', models.IntegerField(blank=True, null=True)),
                ('grahak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
