# Generated by Django 4.1.4 on 2023-02-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('G', 'Grahak'), ('S', 'Sahayak'), ('M', 'MachineMalik')], max_length=10),
        ),
    ]
